template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "lith1251"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-lit"
__UND2C__ = "lt"
__UNDEFINED__ = "Lithuanian"
__UND__ = "lit"
