template = "https://github.com/giellalt/template-lang-und"
rev_id = 263
template_sha = "1bc24707891f274cd9b2690b032d9864fa1205f5"

[replacements]
__GLOTTOLOG_ID__ = "lith1251"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-lit"
__UND2C__ = "lt"
__UNDEFINED__ = "Lithuanian"
__UND__ = "lit"
